name: Shared Build
on:
  workflow_call:
    inputs:
      operating-system:
        type: string
        default: macos-latest
      java-version:
        required: true
        type: string
      cache-playwright:
        type: boolean
        default: false
      codecov:
        type: boolean
        default: false
      codecov-path:
        type: string
        default: build/reports/jacoco/test/jacocoTestReport.xml
      artifact-path:
        type: string
        default: build/reports
      macos-docker:
        type: boolean
        default: false
jobs:
  shared-build:
    runs-on: ${{ inputs.operating-system }}
    steps:
      - uses: douglascamata/setup-docker-macos-action@v1-alpha
        if: ${{ inputs.macos-docker }}
      - name: Fix for docker.sock issue
        if: ${{ inputs.macos-docker }}
        run: |
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - uses: actions/cache@v3
        if: ${{ inputs.cache-playwright }}
        id: cache-playwright
        with:
          path: /Users/runner/Library/Caches/ms-playwright
          key: ms-playwright

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
          cache: 'gradle'
      - run: ./gradlew build
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          retention-days: 30
          name: artifact
          path: ${{ inputs.artifact-path }}
      - uses: codecov/codecov-action@v3
        if: ${{ inputs.codecov }}
        with:
          files: ${{ inputs.codecov-path }}
          verbose: true
