# This workflow will approve and enable auto-merge if required-checks are enabled and the dependency updates are patch/minor.

name: Dependabot merge
on: 
  workflow_call:

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for required checks
        id: check-required
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking PR status checks for PR #${{ github.event.number }}"
          
          # Get PR status - if it's mergeable and not blocked, assume required checks exist
          pr_status=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.number }} --jq '.mergeable_state')
          echo "PR mergeable state: $pr_status"
          
          # Check if there are any pending/failing status checks
          status_checks=$(gh api repos/${{ github.repository }}/commits/${{ github.event.pull_request.head.sha }}/status --jq '.statuses | length')
          echo "Status checks count: $status_checks"
          
          if [ "$pr_status" = "blocked" ] || [ "$status_checks" -gt 0 ]; then
            echo "has-required=true" >> $GITHUB_OUTPUT
            echo "required checks detected (PR state: $pr_status) ✅"
          else
            echo "has-required=false" >> $GITHUB_OUTPUT
            echo "no required checks detected ❌"
          fi

      - name: Dependabot metadata
        if: github.actor == 'dependabot[bot]'
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve minor/patch
        if: |
          steps.check-required.outputs.has-required == 'true' && 
          (steps.metadata.outputs.update-type == 'version-update:semver-minor' || 
           steps.metadata.outputs.update-type == 'version-update:semver-patch')
        run: |
          gh pr review ${{ github.event.number }} --approve
          echo "✅ Auto approved for minor/patch updates"
          gh pr merge --auto --squash "$PR_URL"
          echo "✅ Auto-merge enabled for Dependabot PR"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
