# This workflow will approve and enable auto-merge if required-checks are enabled and the dependency updates are patch/minor.

name: Dependabot merge
on: 
  workflow_call:

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      contents: read
      pull-requests: write
      repository-projects: read
    steps:
      - name: Check for required checks
        id: check-required
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking protection for: repos/${{ github.repository }}/branches/${{ github.ref_name }}/protection"
          protection_response=$(gh api repos/${{ github.repository }}/branches/${{ github.ref_name }}/protection 2>/dev/null || echo "null")
          echo "Protection response: $protection_response"
          
          if [ "$protection_response" = "null" ]; then
            echo "has-required=false" >> $GITHUB_OUTPUT
            echo "no branch protection found ❌"
          else
            check_count=$(echo "$protection_response" | jq -r '.required_status_checks.checks | length // 0')
            echo "Required status checks count: $check_count"
            
            if [ "$check_count" -gt 0 ]; then
              echo "has-required=true" >> $GITHUB_OUTPUT
              echo "has required status checks ✅ ($check_count checks)"
            else
              echo "has-required=false" >> $GITHUB_OUTPUT
              echo "missing required status checks ❌"
            fi
          fi

      - name: Dependabot metadata
        if: github.actor == 'dependabot[bot]'
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve minor/patch
        if: |
          steps.check-required.outputs.has-required == 'true' && 
          (steps.metadata.outputs.update-type == 'version-update:semver-minor' || 
           steps.metadata.outputs.update-type == 'version-update:semver-patch')
        run: |
          gh pr review ${{ github.event.number }} --approve
          echo "✅ Auto approved for minor/patch updates"
          gh pr merge --auto --squash "$PR_URL"
          echo "✅ Auto-merge enabled for Dependabot PR"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
