# This workflow will approve and enable auto-merge if required-checks are enabled and the dependency updates are patch/minor.

name: Dependabot merge
on: 
  workflow_call:

jobs:
  dependabot-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Check for required checks
        id: check-required
        run: |
          if gh api repos/${{ github.repository }}/branches/${{ github.ref_name }}/protection --jq '.required_status_checks.checks | length' 2>/dev/null | grep -q '^[1-9]'; then
            echo "has-required=true" >> $GITHUB_OUTPUT
            echo "has required status checks ✅"
          else
            echo "has-required=false" >> $GITHUB_OUTPUT
            echo "missing required status checks ❌"
          fi

      - name: Dependabot metadata
        if: github.actor == 'dependabot[bot]'
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Auto-approve minor/patch
        if: |
          steps.check-required.outputs.has-required == 'true' && 
          (steps.metadata.outputs.update-type == 'version-update:semver-minor' || 
           steps.metadata.outputs.update-type == 'version-update:semver-patch')
        run: |
          gh pr review ${{ github.event.number }} --approve
          echo "✅ Auto approved for minor/patch updates"
          gh pr merge --auto --squash "$PR_URL"
          echo "✅ Auto-merge enabled for Dependabot PR"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.AUTO_MERGE }}
