# This workflow will perform a semantic release
# For more information see:
#  https://github.com/marketplace/actions/action-for-semantic-release

name: Shared Release
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
jobs:
  shared-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'adopt'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v5
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Publish to Sonatype
        if: steps.semantic.outputs.new_release_published == 'true'
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
        run: |
          ./gradlew publishToSonatype closeAndReleaseStagingRepositories
